quarkus.http.port=8889
# Notification router configuration
notification.kafka.topic=notifications
notification.telegram.authorizationtoken=TELEGRAM_ID


camel.component.kafka.brokers=${kafka.bootstrap.servers}

# Outgoing channel for NotificationResource -> Kafka
mp.messaging.outgoing.notifications-out.connector=smallrye-kafka
mp.messaging.outgoing.notifications-out.topic=${notification.kafka.topic}
