# Notification router configuration
notification.kafka.topic=notifications
notification.telegram.authorizationtoken=CHANGE_ME
notification.telegram.chatid=GalaxiumTravelBot

# Outgoing channel for NotificationResource -> Kafka
mp.messaging.outgoing.notifications-out.connector=smallrye-kafka
mp.messaging.outgoing.notifications-out.topic=${notification.kafka.topic}
