
quarkus.docling.devservices.enabled=false
quarkus.docling.base-url=http://localhost:1234

quarkus.quinoa.package-manager-install.node-version=20.10.0
quarkus.quinoa.package-manager-install=true
quarkus.quinoa.ui-root-path=quinoa

%prod.quarkus.datasource.jdbc.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/galaxium_booking}
%prod.quarkus.datasource.username=${DB_USER:postgres}
%prod.quarkus.datasource.password=${DB_PASSWORD:postgres}
quarkus.hibernate-orm.schema-management.strategy=drop-and-create

quarkus.hibernate-orm.log.sql=true
quarkus.hibernate-orm.log.format-sql=true
quarkus.hibernate-orm.jdbc.statement-batch-size=20

quarkus.langchain4j.openai.base-url = http://langchain4j.dev/demo/openai/v1
quarkus.langchain4j.openai.api-key=${OPENAI_API_KEY:demo}
quarkus.langchain4j.openai.timeout=PT60S

####### Quarkus Flow

# Kafka
quarkus.flow.messaging.defaults-enabled=true


# Flow Engine Inbound CloudEvents (structured JSON)
# Needed by the emitJson method
mp.messaging.incoming.flow-in.connector=smallrye-kafka
mp.messaging.incoming.flow-in.topic=flow-in
mp.messaging.incoming.flow-in.value.deserializer=org.apache.kafka.common.serialization.ByteArrayDeserializer
mp.messaging.incoming.flow-in.key.deserializer=org.apache.kafka.common.serialization.StringDeserializer

# Flow Engine Outbound CloudEvents (structured JSON)
# Needed by the emitJson method
mp.messaging.outgoing.flow-out.connector=smallrye-kafka
mp.messaging.outgoing.flow-out.topic=flow-out
mp.messaging.outgoing.flow-out.value.serializer=org.apache.kafka.common.serialization.ByteArraySerializer
mp.messaging.outgoing.flow-out.key.serializer=org.apache.kafka.common.serialization.StringSerializer

# Flow Engine lifecycle events (useful for telemetry/auditing)
#Not necessary if the following flag is set to false.
quarkus.flow.messaging.lifecycle-enabled=true
mp.messaging.outgoing.flow-lifecycle-out.connector=smallrye-kafka
mp.messaging.outgoing.flow-lifecycle-out.topic=flow-lifecycle-out
mp.messaging.outgoing.flow-lifecycle-out.key.serializer=org.apache.kafka.common.serialization.StringSerializer
mp.messaging.outgoing.flow-lifecycle-out.value.serializer=org.apache.kafka.common.serialization.ByteArraySerializer

# Outgoing channel used by the Newsletter API resource
mp.messaging.outgoing.flow-in-outgoing.connector=smallrye-kafka
mp.messaging.outgoing.flow-in-outgoing.topic=flow-in
mp.messaging.outgoing.flow-in-outgoing.value.serializer=org.apache.kafka.common.serialization.ByteArraySerializer
mp.messaging.outgoing.flow-in-outgoing.key.serializer=org.apache.kafka.common.serialization.StringSerializer

# --- Kafka consumer for flow-out -> Newsletter WebSocket bridge ---
mp.messaging.incoming.flow-out-incoming.connector=smallrye-kafka
mp.messaging.incoming.flow-out-incoming.topic=flow-out
mp.messaging.incoming.flow-out-incoming.value.deserializer=org.apache.kafka.common.serialization.ByteArrayDeserializer
mp.messaging.incoming.flow-out-incoming.auto.offset.reset=earliest


# DEBUG events in the console
# quarkus.log.category."io.quarkiverse.flow.messaging".level=DEBUG
# Change to DEBUG to increase tracing
# quarkus.log.category."io.quarkiverse.flow".level=DEBUG
# Enabled it to increase tracing
quarkus.flow.tracing.enabled=true

quarkus.flow.devui.backend.storage.enabled=true