# Agent Configuration
agent.url=${AGENT_URL:http://localhost:7777}
%test.agent.url=http://localhost:8081

quarkus.vault.secret-config-kv-path=incidence/ai/openai

quarkus.vault.devservices.init-commands=kv put secret/incidence/ai/openai key=demo

# HTTP Server
quarkus.http.port=7777